### ISSUE TITLE
Create error handling for API

### ISSUE THREAD

**Issue by ed-henrique** [yasse-ofc/yasse-api#3]
We are not handling 4xx and 5xx errors right now, but since the API is deployed and working, this is absolutely critical.

**Comment by CA-MKSingh** [comment]
@ed-henrique I would like to work on this, can you please assign this to me?

**Comment by ed-henrique** [comment]
Sure, go for it.

**Comment by CA-MKSingh** [comment]
Hey @ed-henrique , please have a look at it and let me know in case any changes are required.
